muggle/urls.py
from django.urls import path
from . import views

app_name = 'muggle'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('muggle/', include('muggle.urls')),
    path('gallery/', include('gallery.urls')),
    path('storage/', include('storage.urls')),
]

if settings.DEBUG:
    # 开发环境下提供媒体文件服务
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.home, name='home'),
] 

muggle/models.py
from django.db import models

# Create your models here.

muggle/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, '用户名或密码错误')
    return render(request, 'muggle/login.html')

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'muggle/register.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

@login_required
def profile_view(request):
    return render(request, 'muggle/profile.html')

templates/muggle/created.html
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>New Muggle</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Fonts  -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
    <!-- CSS Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Custom styles for this theme -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Feature detection -->
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
</head>


<body>
    <section class="container animated fadeInUp">
        <p href="">{{ username }}</p>
        <p href="">{{ email }}</p>
        <p href="">{{ password }}</p>
        <hr>
        <p href="">注册成功</p>


    </section>

    <!--Global JS-->
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.navgoco.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

templates/muggle/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">登录</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="form-group">
                            <label for="username">用户名</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">密码</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">登录</button>
                    </form>
                    <div class="text-center mt-3">
                        <a href="{% url 'muggle:register' %}">还没有账号？立即注册</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/muggle/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h3>个人资料</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{% static 'images/default-avatar.png' %}" class="img-fluid rounded-circle">
                        </div>
                        <div class="col-md-8">
                            <h4>{{ user.username }}</h4>
                            <p>邮箱：{{ user.email|default:"未设置" }}</p>
                            <p>加入时间：{{ user.date_joined|date:"Y-m-d" }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/muggle/register.html
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>New Muggle</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Fonts  -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
    <!-- CSS Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Custom styles for this theme -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Feature detection -->
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
</head>


<body>
    <section class="container animated fadeInUp">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div id="login-wrapper">
                    <header>
                        <div class="brand">
                            <a href="/" class="logo">
                                <i class="icon-layers"></i>
                                <span>Muggle </span>add new member</a>
                        </div>
                    </header>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                          <h3 class="panel-title">     
                           register
                        </h3>  
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post">
                        {% csrf_token %}
                            {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="alert alert-danger">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <div>
                                <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                            </div>
                        </form>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </section>

    <!--Global JS-->
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.navgoco.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>

</html>